name: Deploy to InfinityFree

on:
    push:
        branches:
            - main

jobs:
    ftp-deploy:
        runs-on: ubuntu-latest

        steps:
            # 1. Baixa o código
            - name: Check out code
              uses: actions/checkout@v4

            # 1.1 Prepara o PHP
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'

            # 1.2 Cria a pasta vendor
            - name: Install Dependencies
              run: composer install --no-dev --optimize-autoloader

            # --- O TRUQUE ESTÁ AQUI ---
            # 1.3 Remove o .gitignore para enganar o robô de deploy
            # Assim ele para de ignorar a pasta vendor e envia ela junto
            - name: Remove gitignore
              run: rm .gitignore
            # --------------------------

            # 2. Envia tudo para o InfinityFree
            - name: FTP Deploy
              uses: SamKirkland/FTP-Deploy-Action@v4.3.4
              with:
                  server: ${{ secrets.FTP_SERVER }}
                  username: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  server-dir: /htdocs/

                  # Como deletamos o .gitignore, precisamos garantir que ele não suba
                  # a pasta .git (que é pesada) manualmente aqui:
                  exclude: |
                      **/.git*
                      **/.git*/**
                      **/node_modules/**
